name = "Ascendant Realms"
author = "Jayden"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df197f8d051f10184ea97ca96264e1ed8fa9c310b807cab008c9cc6701cf7230"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
