name = "Ascendant Realms"
author = "Jayden"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "874e6a855c179bea27ef1f7c7ba5232927d8682640965774ab71fa585a91219a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
