name = "Ascendant Realms"
author = "Jayden"
version = "0.1.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78d1e73e83bcb5d2270cf9869f9ed5a8825fb95b932d7a5cad1e4e4c053df225"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
