
["Spawn Biome Utility Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#generateReport
	generateReport = true
	#suppressMinecraftMobReporting
	suppressMinecraftMobReporting = false
	#fixEmptyNether
	fixEmptyNether = true
	#Use the 'BiomeMobWeight.csv' file to balance Biome spawn values
	balanceBiomeSpawnValues = true
	#Fix min, max values and add nether creatures
	fixSpawnValues = true
	#Use the 'StructMobWeight.csv' file to balance structure spawn values
	balanceStructureSpawnValues = true
	#Mod Name set separated by SemiColons of mods to report.
	includedReportModsSet = "exampleModName;"

["Spawn Placement Fixes"]
	#Add mobs spawning in the air and falling to this list .
	defaultSpawnWeightList = "minecraft:piglin_brute;goblinanddungeon:gob;goblinanddungeon:hobgob;"

["Spawn Weight Values"]
	#minimum Spawn Weight
	#Range: 1 ~ 1000
	minSpawnWeight = 20
	#maximum Spawn Weight
	#Range: 1 ~ 1000
	maxSpawnWeight = 180
	#list of Mod:MobName,DefaultSpawnweight;
	defaultSpawnWeightList = "minecraft:enderman,18;minecraft:witch,28;minecraft:spider,75;minecraft:creeper,70;minecraft:zombie,28;minecraft:skeleton,28;born_in_chaos_v1:dread_hound,55;born_in_chaos_v1:mother_spider,45;born_in_chaos_v1:lifestealer,35;born_in_chaos_v1:scarlet_persecutor,32;irons_spellbooks:cultist,40;irons_spellbooks:magehunter_vindicator,28;alexsmobs:tiger,30;alexsmobs:grizzly_bear,28;alexsmobs:rattlesnake,40;mowziesmobs:naga,22;mowziesmobs:foliaath,28;"

